### ISSUE TITLE
pagination

### ISSUE THREAD

**Issue by aaronshaf** [aaronshaf/dynamodb-admin#1]

**Comment by robertoandrade** [comment]
I noticed that the current pagination feature break when you filter the results, you have to keep on skipping blank pages in order to find the results in the matching pages.

**Comment by lordciccio** [comment]
Yes, it's a known issue. I've been working on this kind of problems in a project recently: the complexity is  due to how dynamo works: scan results can be limited but that limit has nothing to do with filtered results, so when filtering is applied it's not a straightforward task to get only filtered items in pages, or to know total number of pages from the beginning.
I pushed a branch called "pagination" to try to solve the problem, can you give feedback please?
Thank you

**Comment by robertoandrade** [comment]
Works great!

**Comment by lordciccio** [comment]
@aaronshaf, you might just want to check it out so we can merge.

**Comment by robertoandrade** [comment]
One thing I noticed I had to work around was when I add an IndexName to the
scan properties the key you use for pagination no longer works, so was
wondering if there's any way to dynamically pull the KeySchema that truly
reflects the index instead of using the hard coded table key for pagination.

**Comment by aaronshaf** [comment]
@lordciccio Which PR? Seems already merged?

I can cut another release.

**Comment by lordciccio** [comment]
I put it on branch, it's called "pagination"

**Comment by aaronshaf** [comment]
Can you make a pull request out of it?

**Comment by lordciccio** [comment]
sure, just done

**Comment by aaronshaf** [comment]
Merged.

**Comment by aaronshaf** [comment]
@lordciccio What is your npm username? I'll make you a fellow npm owner.

**Comment by lordciccio** [comment]
it's lordciccio :)
thank you

**Comment by aaronshaf** [comment]
Done

**Comment by aaronshaf** [comment]
Thank _you_
