### ISSUE TITLE
Purge table data button

### ISSUE THREAD

**Issue by MatheusVellone** [aaronshaf/dynamodb-admin#14]
I'm always cleaning some of my local dynamo tables to keep it simple and small. But I need to either delete the table and create again, or delete all documents one by one.

What if there was a `Purge Data` button on left of the `Delete table` button ?
Then this button would open a modal to confirm the action. When confirmed it would delete the table and create it again. I prefer the delete table/create again approach over the delete all documents, because it's faster and less unit consuming.

I can try working on a PR if you agree in this functionality :)

**Comment by aaronshaf** [comment]
I have considered this, but I am terrified of people accidentally using this tool with production data. It would need mucho confirmation.

**Comment by MatheusVellone** [comment]
Yeah, I agree with you, running this with production tables and accidental clicks would not be any good.
But some kind of confirmation window (something like a modal) with warnings should be enough.

I'll start working on this, and will also add this "confirmation window" to delete table :)

**Comment by aaronshaf** [comment]
Since this tool is now for DynamoDB Local only, we can totally do purge!

**Comment by corsoa** [comment]
I've also found myself in need of this functionality. +1

**Comment by sashokbg** [comment]
Hello, IMHO in order for this feature to be safe, we need to add the following information on the screen:
Then database endpoint, the region and the last digits of the aws access key.

This information uniquely identifies the database we are using and thus greatly reduces the probability of mistakes.

What are your thoughts ?

PS. This is somehow related to #52 and #53 where the tool does not load the correct database due to incorrect AWS_REGION / ACCESS_KEY

**Comment by rchl** [comment]
Added in v3.1.0
