### ISSUE TITLE
Does not display any data

### ISSUE THREAD

**Issue by henhal** [aaronshaf/dynamodb-admin#54]
I downloaded this tool to give it a go today. I'm using DynamoDB_Local extensively during development and have node servers running locally accessing and modifying data in my local dynamo without any issues.
However, when running `dynamodb-admin`, I just get a page saying there are no tables. I can create new tables, but it doesn't list my existing ones.

I know for a fact that there are tables, since my other scripts, tools and my node apps all find the tables and data running with the same `DYNAMO_ENDPOINT` of `http://localhost:8887`.

Are there any known issues and/or how can I debug dynamo-admin to see where it fails?
(I tried `--debug` and `--verbose` flags with no luck).

**Comment by sashokbg** [comment]
Hello @henhal 
This is most likely related to #52 I also opened a PR to fix the problem (still under validation)

The problem is that a dynamodb instance identified by it's AWS_REGION and AWS_ACCESS_KEY_ID.

What happens is that your dynamodb-admin is pointing to the wrong region / access key.

To overcome this issue you can set them manually by doing so:

```
AWS_ACCESS_KEY_ID=mykey AWS_REGION=my-region-1 dynamodb-admin
```
